const strings = {
  login: 'Login',
  enterEmailID: 'Enter Email Id',
  enterPassword: 'Enter password',
  firstName: 'First Name',
  lastName: 'Last Name',
  emailId: 'Email Id',
  password: 'Password',
  yes: 'Yes',
  no: 'No',
  areYouSure: 'Are you sure?',
  doYouWantToLogout: 'Do you want to logout?',
  logout: 'Logout',
  welcomeBack: 'Welcome Back!',
  dontHaveAnAccount:  "Don't have an account?",
  signUp: 'Sign up',
  pleaseEnterFirstName: 'Please enter first name',
  pleaseEnterPassword: 'Password should have more than 6 charecter and atleast 1 uppercase',
  pleaseEnterValidPassword: 'Please enter valid password',
  createNewAccount: 'Create New Account',
  userAlreadyRegistered: 'User already registered!',
  userIsNotRegisteredYet: 'User not registered yet!',
  invalidPassword: 'Invalid password!',
  camera: 'Camera',
  photoLibrary: 'Photo Library',
  cancel: 'Cancel',
  updateProfile: 'Update Profile',
  update: 'Update'
};

export default strings;